name: "My action"
description: "Test my action"

runs:
  using: "composite" # agrupa pasos comunes para usar en diferentes workflows

  steps:
    - name: "Hello world action"
      run: |
        echo "Hello world action"        
      shell: bash #tienen que llevar la directiva para poder ejecutar 
